# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

In [ ]:
hint(1)

In [ ]:
answer(1)

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np
rng = np.random.default_rng(42)

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

In [ ]:
np.show_config()

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
arr = np.zeros(10) # OR np.zeros( (10) ) / np.zeros( shape=(10,) )
arr

#### 4. How to find the total memory size of any array (★☆☆)

In [ ]:
arr.nbytes  # .itemsize for each ele, .size for number of ele
# dont use sys.getsizeof(arr[0]) , gives new Python scalar object wrapper's size

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.add.__doc__

In [ ]:
np.info(np.add)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
arr = np.zeros(10)
arr[4] = 1
arr

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr = np.arange(10,50,1)
arr

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr[::-1]

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
np.arange(0,9).reshape(3,3)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr = np.array([1,2,0,0,4,0])
print(  list(filter(lambda x: x!=0, arr))   ) # it will be list, less efficient
# or
print(  np.nonzero(arr) )   # its index

print(  arr[np.nonzero(arr)] )
print(  arr[arr!=0] )   # a boolean mask: [ True  True False False  True False]

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)   # k=-1 (1 line down diagonal 1 starts)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
# OR modern approach
rng = np.random.default_rng(42)
rng.random((3,3,3))             # Uniform [0,1)
# rng.standard_normal((3, 3, 3))    # Standard normal

In [ ]:
# Or simply use this
np.random.random((3,3,3)) # OR np.random.rand(3,3,3)

## So, re-use ```rng```
 
```rng = np.random.default_rng(42)
rng.random_function(size_in_tuple)```

In [ ]:
# Each run, start fresh - get same random output every time
rng = np.random.default_rng(42)   # No seed - different output each time
# print(rng.random((3, 4)))  # Etc same output every time
rng

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
# arr = np.random.randint(1,100,(10,10))
arr = rng.integers(1,100,(10,10))   # 100 is exclusive
arr

In [ ]:
# for reduction operations both work but arr.method() is recommended
arr.min() , np.max(arr)

In [ ]:
np.max(arr) == 99   # treated as False

In [ ]:
np.True_ == True, np.True_ is True

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
# np.random.rand(30,30).mean()

rng.random((30,30)).mean()

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
arr = np.ones((5,10))
arr

In [ ]:
arr[1:-1, 1:-1] = 0     # arr[rowsindexes, colmsindexes] or just arr[rowsindexes]
arr

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
Opposite of above

In [ ]:
ar = np.ones((5,10))    # alt way of above # OR, np.pad
ar

In [ ]:
ar[:, [0,-1]] = 0
ar

In [ ]:
ar[[0,-1], :] = 0
ar

In [ ]:
# OR size 3,8 + 2,2 = 5,10
np.pad(np.ones((3,8)), pad_width=1, mode='constant', constant_values=0)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
a = np.array([1,2,np.nan,3])
b = np.array([1,2,np.nan,3])

a is b

In [ ]:
np.astype(np.array([np.nan]), np.int8)  # position-only arg

In [3]:
print(0 * np.nan)       # except != every nan ops = nan
print(np.nan == np.nan)
print(np.inf > np.nan)  # Comparisons with nan are always False.
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)   # if deno != 2 and deno is in x/10 fraction - can't be precisely calculated in binary, 
# so cant be exactly same. ex 0.1 = 1/10 , 0.2 = 2/10 , 0.3 = 3/10, 0.4 = 4/10, 
# exactly same for -> 0.5 = 5/10 = 1/2, 0.25 = 25/100 = 1/4

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [4]:
np.diag(v=[1,2,3,4], k=-1)      # Extract (for 2D) OR construct (for 1D ip) a diagonal array.

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [5]:
x = np.array([  [1,2],
                [3,4]]  )
np.diag(x)  # invalid value of k will return []

array([1, 4])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
arr = np.zeros((8,8))
arr

In [ ]:
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
arr

In [6]:
M = np.fromfunction(lambda i, j: (i + j) % 2, (8, 8), dtype=int) # i-th row, j-th col
M

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [7]:
np.unravel_index(99,(6,7,8))    # np.argmax(), which returns the index of the largest value as a single flat number. 

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [8]:
arr = np.fromfunction(lambda i,j: (i+j)%2, (8,8))
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
base_pattern = np.array([[0, 1], [1, 0]])
np.tile(base_pattern, (4, 4))

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
# arr = np.random.random_integers(1,100,(5,5))
arr = rng.integers(1,100,(5,5))
arr

In [ ]:
( arr - np.mean(arr) ) / np.std(arr)

In [ ]:
# or directly by
rng.normal(loc=0, scale=1, size=(5,5))
# rng.standard_normal((5,5))

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
mera_datatype = np.dtype(
    [("r", np.ubyte),   # unsigned byte consists of 1 byte ie 8 bits. max values = 2^8=256 so 0~255, where 255 is Full intensity
    ("g", np.ubyte),
    ("b", np.ubyte),
    ("a", np.ubyte)]    # alpha... full transparent = 0 , opaque = 255
)
mera_datatype

In [ ]:
# Create an array with this dtype
color_arr = np.array([(255, 0, 0, 255), (0, 255, 0, 128)], dtype=mera_datatype)

# Access a specific field
print(color_arr['r'])  # Output: [255, 0]

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
# mat1 = np.random.randint(1,10,(5,3))
# mat2 = np.random.randint(2,20,(3,2))

mat1 = rng.integers(1,10,(5,3))
mat2 = rng.integers(2,20,(3,2))

np.matmul(mat1,mat2)    # OR mat1 @ mat2, in 2d dot product is also same

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
# arr = np.random.randint(1,10,10)

arr = rng.integers(1,10,10)
print(arr)
arr[(3 <= arr) & (arr <= 8)] *= -1  # boolean mask
print(arr)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1)) # 9
# from numpy import *   # not recommended
print(sum(range(5),-1)) # 10 | actually axis=-1

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [9]:
Z = rng.integers(-10,12,10)
print(Z)
# print(  Z**Z  )            # z^z , Integers to negative integer powers are not allowed
# print(  2 << Z >> 2  )     # left shift of negative is invalid. Formula = a×(2^±n) here a=2,n=z, + for left shift
print(  Z <- Z  )         # same as, Z < -Z
print(  1j*Z  )           # -2,-10 --> -0. -2.j    -0. -10.j
print(  Z/1/1 )           # (Z/1)/1
# print(  Z<Z>Z )         # same as (Z < Z) and (Z > Z) / `and` is invalid of np.array
                # The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
mask = (Z > -5) & (Z < 5)
print(mask.all())

[-9  7  4 -1 -1  8 -9  5 -6 -8]
[ True False False  True  True False  True False  True  True]
[-0.-9.j  0.+7.j  0.+4.j -0.-1.j -0.-1.j  0.+8.j -0.-9.j  0.+5.j -0.-6.j
 -0.-8.j]
[-9.  7.  4. -1. -1.  8. -9.  5. -6. -8.]
False


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
np.array([1]) / np.array([-0.0])
```

In [ ]:
# all produces warning
a = np.array(0) / np.array(0)
print(a)    # np.float64(nan)
b = np.array(0) // np.array(0)
print(b)    # np.int64(0)
c = np.array([np.nan]).astype(int) #.astype(float)
print(c)    # –9,223,372,040,000,000,000
# NumPy forces the conversion (like NaN, inf, or overflowing values TO int), NumPy casts to the lowest possible int for that dtype  

print(  np.array([1]) / np.array([0.0])     )    # array([inf])
print(  np.array([1]) / np.array([-0.0])    )    # 0.0 == -0.0 , but are different numbers


nan
0
[-9223372036854775808]
[inf]
[-inf]


C:\Users\sk\AppData\Local\Temp\ipykernel_1876\2021127531.py:2: RuntimeWarning: invalid value encountered in divide
  a = np.array(0) / np.array(0)
C:\Users\sk\AppData\Local\Temp\ipykernel_1876\2021127531.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  b = np.array(0) // np.array(0)
C:\Users\sk\AppData\Local\Temp\ipykernel_1876\2021127531.py:6: RuntimeWarning: invalid value encountered in cast
  c = np.array([np.nan]).astype(int) #.astype(float)
C:\Users\sk\AppData\Local\Temp\ipykernel_1876\2021127531.py:10: RuntimeWarning: divide by zero encountered in divide
  print(  np.array([1]) / np.array([0.0])     )    # array([inf])
C:\Users\sk\AppData\Local\Temp\ipykernel_1876\2021127531.py:11: RuntimeWarning: divide by zero encountered in divide
  print(  np.array([1]) / np.array([-0.0])    )    # 0.0 == -0.0 , but are different numbers


#### 29. How to round a float array, away from zero? (★☆☆)

###### like [-2.3, -1.1, 0.2, 1.4] -> [-3. -2.  1.  2.]

In [ ]:
Z = rng.uniform(-10, 10, size=5)    # uniform gives float
print(Z)

print(np.copysign(np.ceil(np.abs(Z)), Z))           # np.copysign(magnitude, sign_source)

# More readable but less efficient
# print(np.where(Z>0 ))   # gives index, same as Z>0
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

# wrong way
print(np.trunc(Z))
print(np.floor(Z))


#### 30. How to find common values between two arrays? (★☆☆)

In [13]:
a1 = np.array([2,10,33,22,1,0,23,1,-1])
print(a1)
a2 = np.array([20,1,3,2,8,00,2,1,-1])
print(a2)

print(np.intersect1d(a1,a2))

[ 2 10 33 22  1  0 23  1 -1]
[20  1  3  2  8  0  2  1 -1]
[-1  0  1  2]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [14]:
np.geterr()

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [ ]:
# change error handling behavior and store previous settings
previous_settings = np.seterr(all='raise')
previous_settings

In [ ]:
# Back to sanity
np.seterr(**previous_settings)

In [ ]:
# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

In [ ]:
import warnings # silence every warning from every library (NumPy, pandas, sklearn, etc.) in one go
# warnings.filterwarnings("ignore")     # one of "error", "ignore", "always", "default", "module", or "once"
warnings.filterwarnings("default")  

In [ ]:
Z = np.ones(1) / 0
Z

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)    # nan ; 1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [15]:
import datetime
tode = datetime.date.today()    # or datetime

yesterday = tode - datetime.timedelta(days=1)
tomorrow = tode + datetime.timedelta(days=1)

print(yesterday)
print(tode)
print(tomorrow)

2025-12-26
2025-12-27
2025-12-28


In [ ]:
# or using np

yesterday = np.datetime64('today') - np.timedelta64(1)      # coercion ie forced/automatic type conversion to 'D'
tode      = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1, 'D')

print(yesterday, tode, tomorrow, sep='\n')  # numpy.datetime64

##### Other supported units
```
Y  (years)
M  (months)
W  (weeks)
D  (days)
h  (hours)
m  (minutes)
s  (seconds)
ms (milliseconds)
us (microseconds)
ns (nanoseconds)
ps (picoseconds)
fs (femtoseconds)
as (attoseconds)
```

In [17]:
# Fixed Units: Safe to mix (Day and smaller).

# Variable Units: Year (Y) and Month (M).

# The Rule: You cannot mix Fixed and Variable because the math becomes ambiguous.

# FIX: Convert Year to Days (assuming 365) then add
year_in_days = np.timedelta64(1, 'Y').astype('timedelta64[D]')
result = year_in_days + np.timedelta64(1, 'D') 
# result is 366 days
print(result.dtype)

timedelta64[D]


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
start = np.datetime64('2025-08-01')
end   = np.datetime64('2025-09-01')

dates = np.arange(start, end, dtype='datetime64[D]')    # [D] - days.. ms , W
dates

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
arr = rng.uniform(1, 10, 5)
arr

In [ ]:
print(  np.floor(arr)   )
print(  np.trunc(arr)   )   # np.fix(arr)
print(  arr // 1        )
print(  arr.astype(int) )   # np.astype(arr, int)
print(  arr - arr%1     )

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)   #  Broadcast
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1)) # Construct an array by repeating A the number of times given by reps.
                        # 5 → repeat rows 5 times , 1 → repeat columns once
print(Z)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
# defining generator
def generate():
    for x in range(10):
        yield x
# OR
def generate():
    yield from range(10)

In [ ]:
gen = (x for x in range(10))
print(  np.fromiter(gen, int)                           )   # numpy.int64
print(  np.fromiter(generate(), dtype=int, count=-1)    )   # count=-1 means all, 50 for first 50 etc

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
np.finfo('float16') # FYI, similarly np.iinfo(np.int8) etc

In [ ]:
arr = rng.uniform(0, 1, 10)
arr2 = np.clip(arr, 1e-6, 1 - 1e-6)  # if value is 0 it will be 0.000001
arr2

# more efficient
# eps = np.finfo(float).eps
# arr2 = np.clip(arr, eps, 1 - eps)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr = rng.uniform(0, 1+ 1e-10, 10)
sortedarr = np.sort(arr)
print(sortedarr)

In [ ]:
arr.sort()  # in-place sort
arr

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
arr = rng.uniform(0, 1+ 1e-10, 10)
sum(arr)
s = arr.sum()       # faster
np.add.reduce(arr)  # fastest uses ufunc directly

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [ ]:
arr1 = rng.integers(1,10,5)
arr2 = rng.integers(1,10,5)
print( arr1==arr2 )             # these 3 Not good for floats because of rounding errors.
print( np.equal(arr1,arr2) )
print( np.array_equal(arr1,arr2) )  # single boolean


print( np.allclose(arr1,arr2) ) # rtol= , atol= , equal_nan=  False
                                # good for floats as they are never exactly equal.
                                # Works elementwise and then AND-reduces to a single boolean.
print( np.isclose(arr1, arr2).all())  # Same

# print( np.testing.assert_allclose(arr1, arr2) ) # no op, raises error if all not same within tolerance

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
arr = np.array([1, 2, 3])
arr.flags.writeable = False
arr[0] = 100   # raises ValueError: assignment destination is read-only

In [ ]:
arr.flags

# c -> c lang / row style ie Memory is laid out like: row1 → row2 → row3…
# f -> fortran / column-major style
# OWNDATA -> This array owns its memory (or not). Not a view, not a slice, not referencing another array.
# WRITEABLE -> .view()/np.frombuffer() makes it false
# ALIGNED -> CPU alligned, god for performance
# WRITEBACKIFCOPY -> legacy NumPy “COPY_IF_NEEDED” semantics. modifications to the temporary array would be written back to the original.

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
pts = rng.standard_normal((10, 2))
print(pts)

x = pts[:, 0]
y = pts[:, 1]

# polar coordinates
r = np.sqrt(x**2 + y**2)        # radius
theta = np.arctan2(y, x)        # angle in radians

polar = np.stack((r, theta), axis=1)   # along columns
print(theta)
print(polar)

In [ ]:
a1 = np.array([1,2,3])
a2 = np.array([1,2,5])
np.stack( (a1,a2), axis=1 )

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
arr = rng.integers(1,100,10)
arr[arr == arr.max()] = 0
print(arr)

# np.where(arr==max(arr),0,arr)

In [ ]:
a = np.array([[4, 1], [np.nan, 3]]) 
np.argmax(a), np.argmin(a)      # returns first NaN index

In [ ]:
# fix
np.nanargmax(a), np.nanargmin(a)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [ ]:
np.iinfo(int), np.iinfo(np.int8), np.iinfo(np.int64), np.iinfo('int'), np.iinfo(np.int32)   # similarly finfo

In [ ]:
np.iinfo(np.int32).max      # uint16, float64

#### 49. How to print all the values of an array? (★★☆)
as, normally numpy shortens large arrays like: array([1, 2, 3, ..., 999, 1000])

In [ ]:
np.get_printoptions()

In [ ]:
np.set_printoptions(threshold=float("inf")) # Or, sys.maxsize or default 1000 (If the array has more than 1000 elements, NumPy will truncate the output and show)
Z = np.zeros((4,120))
print(Z)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
matrix = np.array([ [10, 20],
                    [30, 4.5] ])
scalar_m = 14

# 1. Calculate the difference across the entire flattened array
abs_diff_m = np.abs(matrix - scalar_m)

# 2. Use argmin on the flattened array
index_flat = np.argmin(abs_diff_m)

# 3. Use unravel_index to convert the flat index back to (row, col) coordinates
row, col = np.unravel_index(index_flat, matrix.shape)

closest_value_m = matrix[row, col]
closest_value_m

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
# Define the structure of the array using a dtype
point_dtype = np.dtype([
    ('position', 'f8', (2,)),  # 'f8' for float64, (2,) for a pair of (x, y)
    ('color',    'u1', (3,))   # 'u1' for unsigned int 8-bit (0-255), (3,) for (r, g, b)
])          
# FYI, f8 -> float with 8 bytes=64 bits. so, float64. similarly, i4, u1, b1 for boolean

print(point_dtype)

structured_array = np.array([
    ((10.5, 20.1), (255, 0, 0)),     # Point 1: (10.5, 20.1) and Red
    ((5.0, -1.2),  (0, 128, 255)),   # Point 2: (5.0, -1.2) and Aqua-Blue
    ((99.9, 0.0),  (50, 50, 50))     # Point 3: (99.9, 0.0) and Dark Gray
], dtype=point_dtype)

print(structured_array)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
pts = rng.integers(1,10,(100,2))
dists = np.linalg.norm(pts[1:] - pts[:-1], axis=1)
dists

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [ ]:
# There is no true in-place dtype conversion in NumPy. Dtype change ⇒ new memory, always.

ar = rng.uniform(10,20,(10,5)).astype(np.float32)
print(ar)

ar = ar.astype(np.int32, copy=False)
print(ar)

#### 54. How to read the following file (file1.txt)? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
arr = np.genfromtxt('file1.txt', delimiter=',')
arr, arr.dtype

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
arr = np.ndenumerate(arr)
print(*arr)     # (0, 0), np.float64(1.0) ...

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
def

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
m, n = 5, 6   # shape
p = 7         # number of elements to place

arr = np.zeros((m, n), dtype=int)

# pick p unique flat indices
idx = rng.choice(m*n, size=p, replace=False)    # from np.arange(m*n) select p no of items
print(idx)

# assign them
values = rng.integers(10, 50, size=p)
arr.flat[idx] = values
print(arr)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = rng.random((5, 4))
print(X)

# print(X.mean())     # entire mean

Y = X - X.mean(axis=1, keepdims=True)   # keepdims keeps size to (n, 1)
Y

#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
arr[:, 1:2]

In [ ]:
arr = np.array([
    [3, 7, 1],
    [2, 5, 9],
    [8, 1, 4]
])

arr_sorted = arr[  arr[:, 1].argsort()  ]   # sorted index
arr_sorted

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
arr = np.array([
    [3, np.nan, 1],
    [2, np.nan, 9],
    [8, np.nan, 4]
])

# print(  np.isnan(arr)  )    # boolean matrix
# print(  np.isnan(arr).all() )   # False
print(  np.isnan(arr).all(axis=0) )   # [False  True False]

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
Z = rng.uniform(0,1,(10,3))
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()] # without flat multiple answer for n-dim
print(m)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
a = np.array([[1, 2, 3]])   # shape (1,3)
b = np.array([[4], [5], [6]])  # shape (3,1)

it = np.nditer([a, b, None])

for x, y, z in it:
    z[...] = x + y

print(it.operands[2])
# or without iter
print(a+b)

In [ ]:
a = np.array([[1, 2, 3]])   # shape (1,3)
b = np.array([[4], [5], [6]])  # shape (3,1)
out = np.empty((3,3)) 

it = np.nditer([a, b, out], op_flags=[['readonly'], ['readonly'], ['writeonly']])

for x, y, z in it:
    z[...] = x + y

print(out)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
a = np.array([0, 0, 0, 0, 0])
idx = np.array([0, 1, 1, 3])   # index 1 is repeated

np.add.at(a, idx, 1)   # in-place, a[idx] += 1 does NOT handle repeated indices, better than bincount as it supports sparse or negative indices 

print(a)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = np.array([10, 20, 30, 40])
I = np.array([0, 2, 2, 1])   # notice index 2 repeats

F = np.zeros(4)

np.add.at(F, I, X)

print(F)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
arr = np.array([    # shape of (2, 2, 2, 3) -> last 2 is row and col
    [
        [[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 9],
         [10,11,12]]
    ],

    [
        [[2, 1, 0],
         [3, 3, 3]],

        [[5, 5, 5],
         [1, 1, 1]]
    ]
])

print( arr.sum(axis= (-2,-1)))   # Sum over (-2,-1): axis 2 and 3 → remove last 2 and 3, new shape 2,2

In [ ]:
arr[0,0]  # this sum is of result[0,0] ie 1+2+3+4+5+6=21

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
# def printer(var): # HW: takes one or multiple input prints variable name, then the respective value (like x: next line 8), each in newline. and for this cell output in jupyter nb don't collapse
#     print(f"{var}: var")

In [ ]:
D = rng.uniform(0,1,100)     # wgt/vals
S = rng.integers(0,10,100)   # Index
print(D, S, sep='\n')
D_sums = np.bincount(S, weights=D) # in S ->  ??
D_counts = np.bincount(S)   # in S -> 0 is repeated ... time, then 1 is repeated ... time, upto max ele of the array S ??
print('D_counts: ')
print(D_counts)
D_means = D_sums / D_counts
print(D_means)

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = rng.uniform(0,1,(5,5))
B = rng.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))   # OR, np.diag( A*B )

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
vec = np.array([1, 2, 3, 4, 5])

new = np.zeros( (len(vec) + 3*((len(vec)-1) )))
print(new)
new[::4]= vec   # sec-si
print(new)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [ ]:
a = np.ones((5,5,3))
b = np.ones((5,5))
res = a* b.reshape((5,5,1)) # OR, C = A * B[:, :, None] same thing
res.shape

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(  arr[0,2,1][:]  )  # error, first [] as its 2d array and also [:] will fail as it'll be just a value
# arr[[2,1,0]]  # select multiple rows
arr[[0, 2]] = arr[[2, 0]]
print(arr)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])  # A
A = np.repeat(np.arange(len(C)), C)
print(A)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

arr = np.arange(20)
print(np.cumsum(arr))
print(moving_average(arr, n=3))

In [ ]:
# sliding window - easier
from numpy.lib.stride_tricks import sliding_window_view

arr = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
Z = np.array([1,2,3,4,5,6]) 
result = np.vstack([Z[i:i+3] for i in range(len(Z)-2)])
print(result)

In [ ]:
# similar to sliding window - easier
from numpy.lib.stride_tricks import sliding_window_view

Z = np.array([1,2,3,4,5,6])
out = sliding_window_view(Z, window_shape=3)

print(out)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
arr = np.array([True, False, True])
np.logical_not(arr, out=arr)    # OR, arr ^= True # ^ in NumPy means bitwise XOR for int, logical XOR for bool
print(arr)

In [ ]:
arr = np.array([1, False, 3.01, -2])        # float64, false means 0
# arr = ~arr   # not inplace here error as its mixed types
# arr[:] = ~arr # inplace but here error as its mixed types
print (np.negative(arr))  # OR arr *= -1  # [-1.  , -0.  , -3.01,  2.  ]

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])    # generate, R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]

from numpy.lib.stride_tricks import sliding_window_view, as_strided
print(  sliding_window_view(Z, 4)  )

# R = [ Z[i:i+4] for i in range(len(Z)-3)   ]   # pythonic, so slow
# print(R)

#### 82. Compute a matrix rank (★★★)

In [ ]:
rank = np.linalg.matrix_rank(Z)
print(rank)

#### 83. How to find the most frequent value in an array?

In [ ]:
Z = rng.integers(10,20,10)
print(Z)
print(np.bincount(Z))   # index=integer, value=freq
print(np.bincount(Z).argmax())    # finds freq, then index of max freq

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
arr = rng.integers(1,11,(10,10))
arr

In [ ]:
print(np.lib.stride_tricks.sliding_window_view(Z, window_shape=(3, 3)))

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)