# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py
hint(1)
answer(1)

import numpy as np
rng = np.random.default_rng(42)

hint: import … as
import numpy as np


#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
# import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

In [ ]:
np.show_config()

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
arr = np.zeros(10) # OR np.zeros( (10) ) / np.zeros( shape=(10,) )
arr

#### 4. How to find the total memory size of any array (★☆☆)

In [ ]:
arr.nbytes  # .itemsize for each ele, .size for number of ele
# dont use sys.getsizeof(arr[0]) , gives new Python scalar object wrapper's size

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
print(np.add.__doc__)

In [ ]:
np.info(np.add)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
arr = np.zeros(10)
arr[4] = 1
arr

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr = np.arange(10,50,1)
arr

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr[::-1]

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
np.arange(0,9).reshape(3,3)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr = np.array([1,2,0,0,4,0])
print(  list(filter(lambda x: x!=0, arr))   ) # it will be list, less efficient
# or
print(  np.nonzero(arr) )   # its index

print(  arr[np.nonzero(arr)] )
print(  arr[arr!=0] )   # a boolean mask: [ True  True False False  True False]

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)   # k=-1 (1 line down diagonal 1 starts)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
# Modern approach
rng = np.random.default_rng(42)
rng.random((3,3,3))             # Uniform [0,1)
# rng.standard_normal((3, 3, 3))    # Standard normal

In [ ]:
# Or simply use this
np.random.random((3,3,3)) # OR np.random.rand(3,3,3)

## So, re-use ```rng```
 
```rng = np.random.default_rng(42)
rng.random_function(size_in_tuple)```

In [ ]:
# Each run, start fresh - get same random output every time
rng = np.random.default_rng(42)   # No seed - different output each time
# print(rng.random((3, 4)))  # Etc same output every time
rng

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
# arr = np.random.randint(1,100,(10,10))
arr = rng.integers(1,100,(10,10))   # 100 is exclusive
arr

In [ ]:
# for reduction operations both work but arr.method() is recommended
arr.min() , np.max(arr)

In [ ]:
np.max(arr) == 100   # np.False_ treated as False

In [ ]:
np.True_ == True, np.True_ is True

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
# np.random.rand(30,30).mean()

rng.random((30,30)).mean()    # axis=None

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
arr = np.ones((5,10))
arr

In [ ]:
arr[1:-1, 1:-1] = 0     # arr[rowsindexes, colmsindexes] or just arr[rowsindexes]
arr

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
Opposite of above

In [ ]:
ar = np.ones((5,10))    # alt way of above # OR, np.pad
ar

In [ ]:
ar[:, [0,-1]] = 0
ar

In [ ]:
ar[[0,-1], :] = 0
ar

In [ ]:
# OR size 3,8 + 2,2 = 5,10
np.pad(np.ones((3,8)), pad_width=1, mode='constant', constant_values=0)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
a = np.array([1,2,np.nan,3])
b = np.array([1,2,np.nan,3])

a is b

In [ ]:
np.astype(np.array([np.nan]), np.int8)  # position-only arg

In [ ]:
print(0 * np.nan)       # except != every nan ops = nan
print(np.nan == np.nan)
print(np.inf > np.nan)  # Comparisons with nan are always False.
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)   # if deno != 2^n and deno is in x/10 fraction - can't be precisely calculated in binary, 
# so cant be exactly same. ex 0.1 = 1/10 , 0.2 = 2/10 , 0.3 = 3/10, 0.4 = 4/10, 
# exactly same for -> 0.5 = 5/10 = 1/2, 0.25 = 25/100 = 1/4

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
np.diag(v=[1,2,3,4], k=-1)      # Extract (for 2D) OR construct (for 1D ip) a diagonal array.

In [ ]:
x = np.array([  [1,2],
                [3,4]]  )
np.diag(x)  # invalid value of k will return []

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
arr = np.zeros((8,8))
arr

In [ ]:
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
arr

In [ ]:
M = np.fromfunction(lambda i, j: (i + j) % 2, (8, 8), dtype=int) # i-th row, j-th col, dtype of i&j is int
M

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
np.unravel_index(99,(6,7,8))    # np.argmax(), which returns the index of the largest value as a single flat number. 

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
arr = np.fromfunction(lambda i,j: (i+j)%2, (8,8))
arr

In [ ]:
base_pattern = np.array([[0, 1], [1, 0]])
np.tile(base_pattern, (4, 4))

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
# arr = np.random.random_integers(1,100,(5,5))
arr = rng.integers(1,100,(5,5))
arr

In [ ]:
( arr - np.mean(arr) ) / np.std(arr)

In [ ]:
# or directly by
rng.normal(loc=0, scale=1, size=(5,5))
# rng.standard_normal((5,5))

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
mera_datatype = np.dtype(
    [("r", np.ubyte),   # unsigned byte consists of 1 byte ie 8 bits. max values = 2^8=256 so 0~255, where 255 is Full intensity
    ("g", np.ubyte),
    ("b", np.ubyte),
    ("a", np.ubyte)]    # alpha... full transparent = 0 , opaque = 255
)
mera_datatype

In [ ]:
# Create an array with this dtype
color_arr = np.array([(255, 0, 0, 255), (0, 255, 0, 128)], dtype=mera_datatype)

# Access a specific field
print(color_arr['r'])  # Output: [255, 0]

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
# mat1 = np.random.randint(1,10,(5,3))
# mat2 = np.random.randint(2,20,(3,2))

mat1 = rng.integers(1,10,(5,3))
mat2 = rng.integers(2,20,(3,2))

np.matmul(mat1,mat2)    # OR mat1 @ mat2, in 2d dot product is also same

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
# arr = np.random.randint(1,10,10)

arr = rng.integers(1,10,10)
print(arr)
arr[(3 <= arr) & (arr <= 8)] *= -1  # boolean mask
print(arr)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1)) # 9
# from numpy import *   # not recommended
print(sum(range(5),-1)) # 10 | actually axis=-1

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = rng.integers(-10,12,10)
print(Z)
# print(  Z**Z  )            # z^z , Integers to negative integer powers are not allowed
# print(  2 << Z >> 2  )     # left shift of negative is invalid. Formula = a×(2^±n) here a=2,n=z, + for left shift
print(  Z <- Z  )         # same as, Z < -Z
print(  1j*Z  )           # -2,-10 --> -0. -2.j    -0. -10.j
print(  Z/1/1 )           # (Z/1)/1
# print(  Z<Z>Z )         # same as (Z < Z) and (Z > Z) / `and` is invalid of np.array
                # The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
mask = (Z > -5) & (Z < 5)
print(mask.all())

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
np.array([1]) / np.array([-0.0])
```

In [ ]:
# all produces warning
a = np.array(0) / np.array(0)
print(a)    # np.float64(nan)
b = np.array(0) // np.array(0)
print(b)    # np.int64(0)
c = np.array([np.nan]).astype(int) #.astype(float)
print(c)    # –9,223,372,040,000,000,000
# NumPy forced the conversion (like NaN, inf, or overflowing values TO int), NumPy casts to the lowest possible int for that dtype  
print(  np.array([1]) / np.array([0.0])     )    # array([inf])
print(  np.array([1]) / np.array([-0.0])    )    # 0.0 == -0.0 , but are different numbers

#### 29. How to round a float array, away from zero? (★☆☆)

###### like [-2.3, -1.1, 0.2, 1.4] -> [-3. -2.  1.  2.]

In [4]:
Z = rng.uniform(-10, 10, size=5)    # uniform gives float
print(Z)

print(np.copysign(np.ceil(np.abs(Z)), Z))           # np.copysign(magnitude, sign_source)

# More readable but less efficient
# print(np.where(Z>0 ))   # gives index, same as Z>0
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

print("WRONG WAY")
print(np.trunc(Z))
print(np.floor(Z))

[ 9.51244703  5.22279404  5.72128611 -7.43772735 -0.99228124]
[10.  6.  6. -8. -1.]
[10.  6.  6. -8. -1.]
WRONG WAY
[ 9.  5.  5. -7. -0.]
[ 9.  5.  5. -8. -1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [5]:
a1 = np.array([2,10,33,22,1,0,23,1,-1])
print(a1)
a2 = np.array([20,1,3,2,8,00,2,1,-1])
print(a2)

print(np.intersect1d(a1,a2))

[ 2 10 33 22  1  0 23  1 -1]
[20  1  3  2  8  0  2  1 -1]
[-1  0  1  2]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [6]:
np.geterr()

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [ ]:
# change error handling behavior and store previous settings
previous_settings = np.seterr(all='raise')
previous_settings

In [ ]:
# Back to sanity
np.seterr(**previous_settings)

In [ ]:
# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

In [ ]:
import warnings # silence every warning from every library (NumPy, pandas, sklearn, etc.) in one go
# warnings.filterwarnings("ignore")     # one of "error", "ignore", "always", "default", "module", or "once"
warnings.filterwarnings("default")  

In [ ]:
Z = np.ones(1) / 0
Z

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)    # nan ; 1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [7]:
import datetime
tode = datetime.date.today()    # or datetime

yesterday = tode - datetime.timedelta(days=1)
tomorrow = tode + datetime.timedelta(days=1)

print(yesterday)
print(tode)
print(tomorrow)

2026-01-24
2026-01-25
2026-01-26


In [ ]:
# or using np

yesterday = np.datetime64('today') - np.timedelta64(1)      # coercion ie forced/automatic type conversion to 'D'
tode      = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1, 'D')

print(yesterday, tode, tomorrow, sep='\n')  # numpy.datetime64

##### Other supported units
```
Y  (years)
M  (months)
W  (weeks)
D  (days)
h  (hours)
m  (minutes)
s  (seconds)
ms (milliseconds)
us (microseconds)
ns (nanoseconds)
ps (picoseconds)
fs (femtoseconds)
as (attoseconds)
```

In [8]:
# Fixed Units: Safe to mix (Day and smaller).
# Variable Units: Year (Y) and Month (M).

# The Rule: You cannot mix Fixed and Variable because the math becomes ambiguous.

# FIX: Convert Year to Days (assuming 365) then add
year_in_days = np.timedelta64(1, 'Y').astype('timedelta64[D]')
result = year_in_days + np.timedelta64(1, 'D') 
# result is 366 days
print(result.dtype)

timedelta64[D]


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [19]:
# print(np.datetime64.__doc__)
np.datetime64(30, 'D')  # from 1StJan1970 add 30 days

np.datetime64('1970-01-31')

In [20]:
start = np.datetime64('2025-08-01') # 1970-01-01T00:00:00 (and offset is 0000, timezone is utc) YYYY-MM-DD
end   = np.datetime64('2025-09-01')

dates = np.arange(start, end, dtype='datetime64[D]')    # [D] - days.. ms , W
dates

array(['2025-08-01', '2025-08-02', '2025-08-03', '2025-08-04',
       '2025-08-05', '2025-08-06', '2025-08-07', '2025-08-08',
       '2025-08-09', '2025-08-10', '2025-08-11', '2025-08-12',
       '2025-08-13', '2025-08-14', '2025-08-15', '2025-08-16',
       '2025-08-17', '2025-08-18', '2025-08-19', '2025-08-20',
       '2025-08-21', '2025-08-22', '2025-08-23', '2025-08-24',
       '2025-08-25', '2025-08-26', '2025-08-27', '2025-08-28',
       '2025-08-29', '2025-08-30', '2025-08-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [21]:
A = np.ones(3)
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
A

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [22]:
arr = rng.uniform(1, 10, 5)
arr

array([4.33718222, 9.3408849 , 6.79478608, 8.40485452, 4.99072779])

In [23]:
print(  np.floor(arr)   )
print(  np.trunc(arr)   )   # np.fix(arr)
print(  arr // 1        )
print(  arr.astype(int) )   # np.astype(arr, int)
print(  arr - arr%1     )

[4. 9. 6. 8. 4.]
[4. 9. 6. 8. 4.]
[4. 9. 6. 8. 4.]
[4 9 6 8 4]
[4. 9. 6. 8. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [24]:
Z = np.zeros((5,5))
Z += np.arange(5)   #  Broadcast
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1)) # Construct an array by repeating A the number of times given by reps.
                        # 5 → repeat rows 5 times , 1 → repeat columns once
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [47]:
# defining - generator function
def generate():
    for x in range(10):
        yield x

def master_gen():
    yield from range(3)       # 0, 1, 2
    yield from ["A", "B"]     # "A", "B"
    yield from generate()     # 0 through 9 from your other function
    return 

print(*master_gen())

0 1 2 A B 0 1 2 3 4 5 6 7 8 9


In [54]:
# defining - generator function
def generate():
    for x in range(10):
        yield x
# OR
def generate():
    yield from range(10)
# gen = (x for x in range(10))
# generate    # <function __main__.generate()>
generate()  # <generator object at ...>

<generator object generate at 0x0000021DCD329480>

In [55]:
gen = (x for x in range(10))    # Generator Expression
print(  np.fromiter(gen, int)                           )   # numpy.int64
print(  np.fromiter(generate(), dtype=int, count=-1)    )   # count=-1 means all, 50 for first 50 etc

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [56]:
np.finfo('float16') # FYI, similarly np.iinfo(np.int8) etc

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [57]:
arr = rng.uniform(0, 1, 10)
arr2 = np.clip(arr, 1e-6, 1 - 1e-6)  # if value is 0 it will be 0.000001
arr2

# more efficient
# eps = np.finfo(float).eps
# arr2 = np.clip(arr, eps, 1 - eps)

array([0.22723872, 0.55458479, 0.06381726, 0.82763117, 0.6316644 ,
       0.75808774, 0.35452597, 0.97069802, 0.89312112, 0.7783835 ])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr = rng.uniform(0, 1+ 1e-10, 10)
sortedarr = np.sort(arr)
print(sortedarr)

[0.04380377 0.15428949 0.19463871 0.32582536 0.37045971 0.466721
 0.46955581 0.68304895 0.74476216 0.96750973]


In [59]:
arr.sort()  # in-place sort
arr

array([0.04380377, 0.15428949, 0.19463871, 0.32582536, 0.37045971,
       0.466721  , 0.46955581, 0.68304895, 0.74476216, 0.96750973])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [61]:
arr = rng.uniform(0, 1+ 1e-10, 10)
sum(arr)
s = arr.sum()       # faster
np.add.reduce(arr)  # fastest uses ufunc directly

np.float64(4.667029913454828)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [65]:
arr1 = rng.integers(1,10,5)
arr2 = rng.integers(1,10,5)
print( arr1==arr2 )             # these 3 Not good for floats because of rounding errors.
print( np.equal(arr1,arr2) )
print( np.array_equal(arr1,arr2) )  # single boolean


print( np.allclose(arr1,arr2) ) # rtol= , atol= , equal_nan=  False
                                # good for floats as they are never exactly equal.
                                # Works elementwise and then AND-reduces to a single boolean.
print( np.isclose(arr1, arr2).all())  # Same

# print( np.testing.assert_allclose(arr1, arr2) ) # no op, raises error if all not same within tolerance

[False False  True False False]
[False False  True False False]
False
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
arr = np.array([1, 2, 3])
arr.flags.writeable = False
arr[0] = 100   # raises ValueError: assignment destination is read-only

In [66]:
arr.flags

# c -> c lang / row style ie Memory is laid out like: row1 → row2 → row3…
# f -> fortran / column-major style
# OWNDATA -> This array owns its memory (or not). Not a view, not a slice, not referencing another array.
# WRITEABLE -> .view()/np.frombuffer() makes it false
# ALIGNED -> CPU alligned, god for performance
# WRITEBACKIFCOPY -> legacy NumPy “COPY_IF_NEEDED” semantics. modifications to the temporary array would be written back to the original.

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [67]:
pts = rng.standard_normal((10, 2))
print(pts)

x = pts[:, 0]
y = pts[:, 1]

# polar coordinates
r = np.sqrt(x**2 + y**2)        # radius
theta = np.arctan2(y, x)        # angle in radians

polar = np.stack((r, theta), axis=1)   # along columns
print(theta)
print(polar)

[[ 0.49716074  0.14242574]
 [ 0.69048535 -0.42725265]
 [ 0.15853969  0.62559039]
 [-0.30934654  0.45677524]
 [-0.66192594 -0.36305385]
 [-0.38173789 -1.19583965]
 [ 0.48697248 -0.46940234]
 [ 0.01249412  0.48074666]
 [ 0.44653118  0.66538511]
 [-0.09848548 -0.42329831]]
[ 0.27900582 -0.55410784  1.32259757  2.16608337 -2.63991636 -1.87979305
 -0.76702862  1.54481319  0.97973986 -1.79939161]
[[ 0.51715945  0.27900582]
 [ 0.81198205 -0.55410784]
 [ 0.6453667   1.32259757]
 [ 0.55166919  2.16608337]
 [ 0.75495301 -2.63991636]
 [ 1.25529131 -1.87979305]
 [ 0.67637324 -0.76702862]
 [ 0.48090899  1.54481319]
 [ 0.80132854  0.97973986]
 [ 0.43460425 -1.79939161]]


In [68]:
a1 = np.array([1,2,3])
a2 = np.array([1,2,5])
np.stack( (a1,a2), axis=1 )

array([[1, 1],
       [2, 2],
       [3, 5]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
arr = rng.integers(1,5,10)
arr[arr == arr.max()] = 0
print(arr)

# np.where(arr==max(arr),0,arr)

array([1, 2, 1, 2, 0, 1, 0, 1, 1, 0])

In [ ]:
a = np.array([[4, 1], [np.nan, 3]]) 
np.argmax(a), np.argmin(a)      # returns first max/nan index

(np.int64(2), np.int64(2))

In [71]:
# fix
np.nanargmax(a), np.nanargmin(a)

(np.int64(0), np.int64(1))

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [78]:
np.iinfo(int), np.iinfo(np.int8), np.iinfo(np.int64), np.iinfo('int'), np.iinfo(np.int32)   # similarly finfo

(iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64),
 iinfo(min=-128, max=127, dtype=int8),
 iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64),
 iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64),
 iinfo(min=-2147483648, max=2147483647, dtype=int32))

In [79]:
np.iinfo(np.int32).max      # uint16, float64

2147483647

#### 49. How to print all the values of an array? (★★☆)
as, normally numpy shortens large arrays like: array([1, 2, 3, ..., 999, 1000])

In [ ]:
np.get_printoptions()

In [ ]:
np.set_printoptions(threshold=float("inf")) # Or, sys.maxsize or default 1000 (If the array has more than 1000 elements, NumPy will truncate the output and show)
Z = np.zeros((4,120))
print(Z)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [81]:
matrix = np.array([ [10, 20],
                    [30, 4.5] ])
scalar_m = 14

# 1. Calculate the difference across the entire flattened array
abs_diff_m = np.abs(matrix - scalar_m)

# 2. Use argmin on the flattened array
index_flat = np.argmin(abs_diff_m)

# 3. Use unravel_index to convert the flat index back to (row, col) coordinates
row, col = np.unravel_index(index_flat, matrix.shape)

closest_value_m = matrix[row, col]
print(closest_value_m)

# OR 3rd
closest_value = matrix.flat[index_flat]
print(closest_value)

10.0
10.0


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
# Define the structure of the array using a dtype
point_dtype = np.dtype([
    ('position', 'f8', (2,)),  # 'f8' for float64, (2,) for a pair of (x, y)
    ('color',    'u1', (3,))   # 'u1' for unsigned int 8-bit (0-255), (3,) for (r, g, b)
])          
# FYI, f8 -> float with 8 bytes=64 bits. so, float64. similarly, i4, u1, b1 for boolean

print(point_dtype)

structured_array = np.array([
    ((10.5, 20.1), (255, 0, 0)),     # Point 1: (10.5, 20.1) and Red
    ((5.0, -1.2),  (0, 128, 255)),   # Point 2: (5.0, -1.2) and Aqua-Blue
    ((99.9, 0.0),  (50, 50, 50))     # Point 3: (99.9, 0.0) and Dark Gray
], dtype=point_dtype)

print(structured_array)

In [8]:
print("This text is being sent to the file instead of the screen! 1")
with open('my_log.txt', 'a+') as f:
    print("This text is being sent to the file instead of the screen! 2", file=f)

This text is being sent to the file instead of the screen! 1


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
pts = rng.integers(1,10,(100,2))
dists = np.linalg.norm(pts[1:] - pts[:-1], axis=1)  # from 2nd row, upto last row; 
dists                                               # then compute their distance using root of x^2+y^2 (horizontally ie axis=1)

array([ 2.        ,  7.81024968,  3.16227766,  3.        ,  5.09901951,
        4.24264069,  3.60555128,  7.28010989,  2.        ,  7.61577311,
        0.        ,  5.38516481,  2.23606798,  3.16227766,  2.82842712,
        2.82842712,  4.47213595,  1.        ,  7.        ,  7.28010989,
        7.28010989,  6.70820393,  2.82842712,  2.        ,  7.21110255,
        1.41421356,  7.07106781,  1.        ,  5.83095189,  4.12310563,
        6.32455532,  5.09901951,  6.08276253,  7.        ,  7.61577311,
        4.12310563,  4.12310563,  1.        ,  1.        ,  2.        ,
        5.09901951,  6.08276253,  6.40312424,  1.41421356,  4.24264069,
        1.        ,  2.23606798,  3.60555128,  1.        ,  7.61577311,
        1.        ,  4.12310563,  6.        ,  4.24264069,  3.60555128,
        6.70820393,  3.60555128,  8.06225775,  4.        , 10.63014581,
        7.        ,  8.54400375,  8.54400375,  7.07106781,  1.        ,
        5.        ,  1.        ,  3.        ,  2.        ,  2.  

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [9]:
# There is no true in-place dtype conversion in NumPy. Dtype change ⇒ new memory, always.

ar = rng.uniform(10,20,(10,5)).astype(np.float32)
print(ar)

ar = ar.astype(np.int32, copy=False)
print(ar)

[[19.085808  16.997072  12.6587    19.691763  17.78751  ]
 [17.168901  14.493615  12.722416  10.963909  19.026024 ]
 [14.557763  12.023634  13.0595665 15.792195  11.767728 ]
 [18.566143  17.585196  17.19463   14.3209305 16.273088 ]
 [15.84098   16.498466  10.844443  14.158074  10.4161415]
 [14.939908  13.298613  11.445242  11.03403   15.876446 ]
 [11.70593   19.251202  15.810612  13.4686985 15.909155 ]
 [10.228039  19.585592  14.823034  17.827353  10.8273   ]
 [14.866583  14.90707   19.378265  15.71728   14.734894 ]
 [12.669757  13.31569   15.206724  14.389114  10.216121 ]]
[[19 16 12 19 17]
 [17 14 12 10 19]
 [14 12 13 15 11]
 [18 17 17 14 16]
 [15 16 10 14 10]
 [14 13 11 11 15]
 [11 19 15 13 15]
 [10 19 14 17 10]
 [14 14 19 15 14]
 [12 13 15 14 10]]


#### 54. How to read the following file (file1.txt)? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
arr = np.genfromtxt('file1.txt', delimiter=',')
arr, arr.dtype  # default datatype is float64, for int its int64 etc

(array([[ 1.,  2.,  3.,  4.,  5.],
        [ 6., nan, nan,  7.,  8.],
        [nan, nan,  9., 10., 11.]]),
 dtype('float64'))

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
arr = np.ndenumerate(arr)
print(*arr)     # (0, 0), np.float64(1.0) ...

((0, 0), np.float64(1.0)) ((0, 1), np.float64(2.0)) ((0, 2), np.float64(3.0)) ((0, 3), np.float64(4.0)) ((0, 4), np.float64(5.0)) ((1, 0), np.float64(6.0)) ((1, 1), np.float64(nan)) ((1, 2), np.float64(nan)) ((1, 3), np.float64(7.0)) ((1, 4), np.float64(8.0)) ((2, 0), np.float64(nan)) ((2, 1), np.float64(nan)) ((2, 2), np.float64(9.0)) ((2, 3), np.float64(10.0)) ((2, 4), np.float64(11.0))


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [14]:
m, n = 5, 6   # shape
p = 7         # number of elements to place

arr = np.zeros((m, n), dtype=int)

# pick p unique flat indices
idx = rng.choice(m*n, size=p, replace=False)    # from np.arange(m*n) select p no of items
print(idx)

# assign them
values = rng.integers(10, 50, size=p)
arr.flat[idx] = values
print(arr)

[ 4 15  9  0  8 20 24]
[[39  0  0  0 21  0]
 [ 0  0 39 36  0  0]
 [ 0  0  0 19  0  0]
 [ 0  0 47  0  0  0]
 [40  0  0  0  0  0]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = rng.random((5, 4))
print(X)
# print(X.mean())     # entire mean as default axis=None

Y = X - X.mean(axis=1, keepdims=True)   # keepdims keeps size to (n, 1) 
        # else will be error as unsuported broadcasting between (5,4) and (5,)
        # or use x_mean.reshape()
Y

#### 59. How to sort an array by the nth column? (★★☆)

In [29]:
arr = np.array([
    [3, 7, 1],
    [2, 5, 9],
    [8, 1, 4]
])
            # arr[ rows, cols]
arr_sorted = arr[  arr[:, 1].argsort()  ]   # sorted index
arr_sorted

array([[8, 1, 4],
       [2, 5, 9],
       [3, 7, 1]])

In [43]:
arr = np.array([
    [3, 7, 1],
    [2, 5, 9],
    [8, 1, 4]
])
arr[ 0 ]
arr[ [0] ]
arr[ 0, 1]
arr[ [0,1] ]
arr[ [0,1] ]
arr[ :, 1 ]
# arr[ [:, 1] ]


array([7, 5, 1])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [48]:
arr = np.array([
    [3, np.nan, 1],
    [2, np.nan, 9],
    [8, np.nan, 4]
])

# print(  np.isnan(arr)  )    # boolean matrix
# print(  np.isnan(arr).all() )   # False
print(  np.isnan(arr).all(axis=0) )   # [False  True False]

[False  True False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [49]:
Z = rng.uniform(0,1,(10,3))
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()] # without flat multiple answer for n-dim
print(m)

0.5007411862023423


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
a = np.array([[1, 2, 3]])   # shape (1,3)
b = np.array([[4], [5], [6]])  # shape (3,1)

it = np.nditer([a, b, None])

for x, y, z in it:
    z[...] = x + y

print(it.operands[2])
# or without iter (directly using broadcasting)
print(a+b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [51]:
a = np.array([[1, 2, 3]])   # shape (1,3)
b = np.array([[4], [5], [6]])  # shape (3,1)
out = np.empty((3,3)) 

it = np.nditer([a, b, out], op_flags=[['readonly'], ['readonly'], ['writeonly']])

for x, y, z in it:
    z[...] = x + y

print(out)

[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
a = np.array([0, 0, 0, 0, 0])
idx = np.array([0, 1, 1, 3])   # index 1 is repeated

np.add.at(a, idx, 1)   # in-place, a[idx] += 1 does NOT handle repeated indices, better than bincount as it supports sparse or negative indices 

print(a)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [52]:
X = np.array([10, 20, 30, 40])
I = np.array([0, 2, 2, 1])   # notice index 2 repeats

F = np.zeros(4)

np.add.at(F, I, X)

print(F)

[10. 40. 50.  0.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [53]:
arr = np.array([    # shape of (2, 2, 2, 3) -> last 2 is row and col
    [
        [[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 9],
         [10,11,12]]
    ],

    [
        [[2, 1, 0],
         [3, 3, 3]],

        [[5, 5, 5],
         [1, 1, 1]]
    ]
])

print( arr.sum(axis= (-2,-1)))   # Sum over (-2,-1): axis 2 and 3 → remove last 2 and 3, new shape 2,2

[[21 57]
 [12 18]]


In [54]:
arr[0,0]  # this sum is of result[0,0] ie 1+2+3+4+5+6=21

array([[1, 2, 3],
       [4, 5, 6]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [55]:
# def printer(var): # HW: takes one or multiple input prints variable name, then the respective value (like x: next line 8), each in newline. and for this cell output in jupyter nb don't collapse
#     print(f"{var}: var")

In [56]:
D = rng.uniform(0,1,100)     # wgt/vals
S = rng.integers(0,10,100)   # Index
print(D, S, sep='\n')
D_sums = np.bincount(S, weights=D) # in S ->  ??
D_counts = np.bincount(S)   # in S -> 0 is repeated ... time, then 1 is repeated ... time, upto max ele of the array S ??
print('D_counts: ')
print(D_counts)
D_means = D_sums / D_counts
print(D_means)

[0.69426244 0.58111661 0.19977565 0.80412453 0.71540713 0.738984
 0.13105775 0.1237538  0.92756255 0.39757819 0.30094869 0.48858405
 0.66286421 0.95562326 0.28644623 0.92480843 0.02485949 0.55519804
 0.63397511 0.1058974  0.1403396  0.41911432 0.96623191 0.59604255
 0.93302322 0.80436092 0.4673816  0.78476345 0.01783678 0.109144
 0.82942861 0.79681709 0.23264074 0.53076959 0.60601582 0.86773895
 0.60310716 0.41257157 0.37418404 0.42588209 0.65193103 0.86749063
 0.45389688 0.24783956 0.23666236 0.74601428 0.81656876 0.10527808
 0.06655886 0.59443366 0.14617324 0.82466419 0.31033467 0.14387193
 0.92097047 0.16553172 0.28472008 0.1536134  0.11549006 0.02114802
 0.05539541 0.17464147 0.05338193 0.59114382 0.68071453 0.39363046
 0.3179911  0.50452624 0.87500494 0.85113163 0.04347506 0.18149841
 0.23674487 0.24938758 0.57123265 0.41626243 0.04925412 0.37361414
 0.52375295 0.1016719  0.83345855 0.05196187 0.92484187 0.09911314
 0.84357495 0.90265314 0.97957068 0.80202588 0.77947754 0.64248328

#### 69. How to get the diagonal of a dot product? (★★★)

In [57]:
A = rng.uniform(0,1,(5,5))
B = rng.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))   # OR, np.diag( A*B )

array([1.65314361, 1.51038178, 1.36960298, 0.98062641, 1.68096524])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
vec = np.array([1, 2, 3, 4, 5])

new = np.zeros( (len(vec) + 3*((len(vec)-1) )))
print(new)
new[::4]= vec
print(new)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [59]:
a = np.ones((5,5,3))
b = np.ones((5,5))
res = a* b.reshape((5,5,1)) # OR, C = A * B[:, :, None] same thing
res.shape

(5, 5, 3)

#### 72. How to swap two rows of an array? (★★★)

In [60]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(  arr[0,2,1][:]  )  # error, first [] as its 2d array and also [:] will fail as it'll be just a value
# arr[[2,1,0]]  # select multiple rows
arr[[0, 2]] = arr[[2, 0]]
print(arr)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [7]:
C = np.bincount([1,1,2,3,4,4,6])  # A
A = np.repeat(a= np.arange(len(C)), repeats= C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [11]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

arr = np.arange(20)
print(np.cumsum(arr))
print(moving_average(arr, n=3))

[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [14]:
# sliding window - easier
from numpy.lib.stride_tricks import sliding_window_view

arr = np.arange(20)
print(sliding_window_view(arr, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [16]:
Z = np.array([1,2,3,4,5,6]) 
result = np.vstack([Z[i:i+3] for i in range(len(Z)-2)])
print(result)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [15]:
# similar to sliding window - easier
from numpy.lib.stride_tricks import sliding_window_view

Z = np.array([1,2,3,4,5,6])
out = sliding_window_view(Z, window_shape=3)

print(out)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
arr = np.array([True, False, True])
np.logical_not(arr, out=arr)    # OR, arr ^= True # ^ in NumPy means bitwise XOR for int, logical XOR for bool
print(arr)

In [17]:
arr = np.array([1, False, 3.01, -2])        # float64, false means 0
# arr = ~arr   # not inplace here error as its mixed types
# arr[:] = ~arr # inplace but here error as its mixed types
print (np.negative(arr))  # OR arr *= -1  # [-1.  , -0.  , -3.01,  2.  ]

[-1.   -0.   -3.01  2.  ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [18]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])    # generate, R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]

from numpy.lib.stride_tricks import sliding_window_view, as_strided
print(  sliding_window_view(Z, 4)  )

# R = [ Z[i:i+4] for i in range(len(Z)-3)   ]   # pythonic, so slow
# print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [19]:
rank = np.linalg.matrix_rank(Z)
print(rank)

1


#### 83. How to find the most frequent value in an array?

In [20]:
Z = rng.integers(10,20,10)
print(Z)
print(np.bincount(Z))   # index=integer, value=freq
print(np.bincount(Z).argmax())    # finds freq, then index of max freq

[10 17 16 14 14 18 10 16 12 10]
[0 0 0 0 0 0 0 0 0 0 3 0 1 0 2 0 2 1 1]
10


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [23]:
arr = rng.integers(1,11,(10,10))
arr

array([[ 3,  8,  6,  5,  6,  6,  1,  2,  3,  2],
       [ 5,  7,  7,  5,  9,  6,  1,  8,  6,  7],
       [ 6,  6,  1,  6,  8,  4,  7,  1,  4,  5],
       [10,  3,  3,  5, 10,  9,  1,  3,  9,  1],
       [ 9,  3, 10,  3,  5,  7,  2,  6,  6,  8],
       [10,  7,  5,  5,  5,  9,  4,  2,  4,  1],
       [ 2,  1,  8,  8,  7,  5,  8,  2, 10,  6],
       [10,  2,  5,  7,  5,  5,  2,  4,  3,  4],
       [ 7,  7,  7,  4, 10,  1,  4,  2,  4, 10],
       [ 4, 10,  5,  7,  5,  3,  8, 10,  3,  8]])

In [24]:
print(np.lib.stride_tricks.sliding_window_view(arr, window_shape=(3, 3)))

[[[[ 3  8  6]
   [ 5  7  7]
   [ 6  6  1]]

  [[ 8  6  5]
   [ 7  7  5]
   [ 6  1  6]]

  [[ 6  5  6]
   [ 7  5  9]
   [ 1  6  8]]

  [[ 5  6  6]
   [ 5  9  6]
   [ 6  8  4]]

  [[ 6  6  1]
   [ 9  6  1]
   [ 8  4  7]]

  [[ 6  1  2]
   [ 6  1  8]
   [ 4  7  1]]

  [[ 1  2  3]
   [ 1  8  6]
   [ 7  1  4]]

  [[ 2  3  2]
   [ 8  6  7]
   [ 1  4  5]]]


 [[[ 5  7  7]
   [ 6  6  1]
   [10  3  3]]

  [[ 7  7  5]
   [ 6  1  6]
   [ 3  3  5]]

  [[ 7  5  9]
   [ 1  6  8]
   [ 3  5 10]]

  [[ 5  9  6]
   [ 6  8  4]
   [ 5 10  9]]

  [[ 9  6  1]
   [ 8  4  7]
   [10  9  1]]

  [[ 6  1  8]
   [ 4  7  1]
   [ 9  1  3]]

  [[ 1  8  6]
   [ 7  1  4]
   [ 1  3  9]]

  [[ 8  6  7]
   [ 1  4  5]
   [ 3  9  1]]]


 [[[ 6  6  1]
   [10  3  3]
   [ 9  3 10]]

  [[ 6  1  6]
   [ 3  3  5]
   [ 3 10  3]]

  [[ 1  6  8]
   [ 3  5 10]
   [10  3  5]]

  [[ 6  8  4]
   [ 5 10  9]
   [ 3  5  7]]

  [[ 8  4  7]
   [10  9  1]
   [ 5  7  2]]

  [[ 4  7  1]
   [ 9  1  3]
   [ 7  2  6]]

  [[ 7  1  4]
   [ 1  3  9]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [2]:
Z = rng.integers(10,21,(4,4))
print(Z)
Z_sym = (Z + Z.T) / 2
Z_sym

[[10 18 17 14]
 [14 19 10 17]
 [12 11 15 20]
 [18 18 17 18]]


array([[10. , 16. , 14.5, 16. ],
       [16. , 19. , 10.5, 17.5],
       [14.5, 10.5, 15. , 18.5],
       [16. , 17.5, 18.5, 18. ]])

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [9]:
p, n = 10, 20
M = rng.integers(1,11,(p,n,n))
V = rng.integers(0,21,(p,n,1))

result = (M @ V).sum(axis=0) # shape of M@V is (p, n, 1), after sum at axis0 (ie p) its (n,1)
result

array([[10913],
       [10234],
       [10058],
       [ 9771],
       [11036],
       [10485],
       [10852],
       [10543],
       [10645],
       [10333],
       [10249],
       [10733],
       [10072],
       [10320],
       [ 9903],
       [10299],
       [10568],
       [10863],
       [ 9796],
       [10472]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? So, they are non-overlaping ie Checkerboard pattern type (★★★)

In [22]:
ar = rng.integers(0,11,(16,16))

blocks = np.lib.stride_tricks.sliding_window_view(ar,(4,4))
print(blocks.shape) # shape (13, 13, 4, 4)

# Slice with a step of 4 to remove the overlaps
# result shape becomes (4, 4, 4, 4)
non_overlapping = blocks[::4, ::4]

# Sum the last two dimensions (the 4x4 windows themselves)
block_sum = non_overlapping.sum(axis=(-1, -2))
block_sum

(13, 13, 4, 4)


array([[72, 77, 73, 73],
       [65, 77, 89, 76],
       [97, 66, 51, 72],
       [85, 74, 61, 56]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [44]:
n = 3

# regular way - time complexity is nlogn
ar = rng.integers(1,1001,(16,16))
sorted_ar = np.sort(ar.flatten())[::-1]
sorted_ar[:n]

array([999, 996, 995])

In [47]:
# more efficient way - O(n) - using partition first
n = 3
ar = np.random.randint(1, 1001, (16, 16))

# Flatten first since it's a 2D array
flat = ar.flatten()

# 1. Partition: Everything to the right of index '-n' will be the largest
# This puts the n largest values at the end of the array (unsorted)
partitioned = np.partition(flat, -n)
print(partitioned)

# 2. Slice the last n and sort them if you want descending order
result = np.sort(partitioned[-n:])[::-1]

print(result)

[  1  15  21  29  44  46  47  49  49  53  56  58  59  61  65  69  69  70
  73  81  88  88  95 103 105 106 107 110 114 115 118 128 135 135 136 138
 140 141 146 148 153 162 162 169 172 182 182 193 193 201 208 213 222 222
 228 230 237 239 240 250 251 252 255 266 272 281 283 284 300 303 303 304
 307 312 323 324 327 336 342 342 346 347 347 362 373 386 395 406 412 414
 422 422 425 427 430 436 436 436 454 458 458 461 468 477 488 490 491 495
 496 506 507 507 509 510 513 523 530 531 533 534 540 549 551 551 559 563
 570 573 576 593 607 618 619 623 624 631 637 638 641 642 645 646 647 649
 654 654 660 666 667 668 670 679 679 682 683 686 688 688 696 696 702 709
 716 719 719 719 722 722 726 726 727 728 730 731 733 741 743 743 746 763
 765 767 770 770 772 776 778 781 785 785 788 789 790 791 805 809 811 815
 816 820 823 830 831 832 833 837 838 840 851 852 860 869 873 874 879 880
 883 885 887 891 894 900 902 903 904 907 908 911 915 918 926 928 930 931
 933 935 936 936 937 940 941 941 945 949 950 951 95

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [ ]:
def cartesian_product(*arrays):
    # 1. Create a coordinate grid for every array that is basically cartesian product
    grid = np.meshgrid(*arrays, indexing='ij')
    
    print(np.stack(grid, axis=-1))
    # 2. Reshape each grid to a column and stack them
    return np.stack(grid, axis=-1).reshape(-1, len(arrays))

# Usage:
v1 = np.array([1, 2])
v2 = np.array([4, 5])
v3 = np.array([0])

result = cartesian_product(v1, v2, v3)
print(result)

[[[[1 4 0]]

  [[1 5 0]]]


 [[[2 4 0]]

  [[2 5 0]]]]
[[1 4 0]
 [1 5 0]
 [2 4 0]
 [2 5 0]]


#### 91. How to create a record array from a regular array? ie we want to see a particular column by arr.attribute (★★★)

In [51]:
structured_input = np.array([(1, 'Alice'), (2, 'Bob')],   dtype=[('id', 'i4'), ('name', 'U10')])

# Cast it to a record array
rec = structured_input.view(np.recarray)

print(rec.name) # Result: ['Alice' 'Bob']

['Alice' 'Bob']


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
Z = np.array([0, -13523, 2097132, 2097142, 2097151]).astype(int)
print( Z**3 )

print( Z*Z*Z )

print( np.power(Z,3) )
print( np.einsum('i,i,i->i',x,x,x) ) # Most optimized, Einstein summation -> subscripts, *operands

[                  0      -2472971686667 9223108156580683968
 9223240096088587288 9223358842721533951]
[                  0      -2472971686667 9223108156580683968
 9223240096088587288 9223358842721533951]
[                   0  -178425063580677114  9223218984566907560
  9223350926490726740 -9223274399487387614]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [18]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [2,3,1],
    [7,8,9],
    [3,1,5],
    [2,4,1],
    [3,2,6],
    [1,9,8]
])

B = np.array([
    [1,3],
    [4,2]
])

print( np.isin(A, [1,3]) )
# print( np.isin(A, [1,3]).sum(axis=1) == len([1,3]) )  # basically A(each number) in [1,3] ?

# For each row of B, check membership in rows of A
matches = [(np.isin(A, b_row).sum(axis=1) == len(b_row)) for b_row in B]
matches

[[ True False  True]
 [False False False]
 [False  True  True]
 [False False False]
 [ True  True False]
 [False False  True]
 [ True False False]
 [ True False False]]


[array([ True, False,  True, False,  True, False, False, False]),
 array([False, False, False, False, False,  True, False, False])]

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
A = rng.integers(1,6,(10,3))

# print(A)
# print( A[:, [0]] )
# print(A == A[:, [0]])   # for each row comparing first value with all

rows_unequal = A[~np.all(A == A[:, [0]], axis=1)]
rows_unequal

[[3 5 5]
 [2 5 2]
 [2 4 4]
 [1 5 1]
 [5 1 4]
 [4 4 4]
 [3 4 2]
 [4 3 3]
 [3 3 1]
 [1 2 1]]
[[3]
 [2]
 [2]
 [1]
 [5]
 [4]
 [3]
 [4]
 [3]
 [1]]
[[ True False False]
 [ True False  True]
 [ True False False]
 [ True False  True]
 [ True False False]
 [ True  True  True]
 [ True False False]
 [ True False False]
 [ True  True False]
 [ True False  True]]


array([[3, 5, 5],
       [2, 5, 2],
       [2, 4, 4],
       [1, 5, 1],
       [5, 1, 4],
       [3, 4, 2],
       [4, 3, 3],
       [3, 3, 1],
       [1, 2, 1]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
ar = rng.integers(1,11,(3,4))
print(ar)

# Vectorize the function to apply it to every element
v_bin = np.vectorize(np.binary_repr)

# Width=4 ensures all strings have the same length (padded with 0s)
bin_ar = v_bin(ar, width=4)
print(bin_ar)

[[7 8 8 2]
 [4 5 5 1]
 [6 2 8 7]]
<U4


In [7]:
# FAST
ar = rng.integers(1,11,(3,4))
print(ar)

# The "Shift and Mask" trick
width = 4   # 4 bits: Max 2^4 - 1 = 15  <-- our max input num 10 fits here!
# Create a mask for each bit: like [8, 4, 2, 1]
powers = 1 << np.arange(width)[::-1]
print(powers)

# Unfold the array and compare bits
# Result is shape (3, 4, 4)
bin_matrix = (ar[..., None] & powers > 0).astype(int)

print(bin_matrix[0, 0]) # The binary bits for the first number

[[10  8  4 10]
 [ 5  4 10  4]
 [ 1  5  8  2]]
[8 4 2 1]
[1 0 1 0]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [27]:
ar = rng.integers(1,3,(4,3))
print(ar)

# mask = ar[0,0]==ar[0] # this is for first row; i need to implement this for all rows
# mask.all(axis=-1)

# 1. Extract the first column but keep it 2D (Shape: 3, 1)
first_column = ar[:, [0]]
# 2. Compare the whole array to that first column
# This broadcasts the (3,1) against the (3,4)
mask = (ar == first_column)

# 3. Check if all values in a row are True
result = mask.all(axis=-1)
result

[[2 2 2]
 [1 1 1]
 [1 2 1]
 [2 2 1]]


array([ True,  True, False, False])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# 1. Inner Product (Dot Product)
# Returns: 1*4 + 2*5 + 3*6 = 32
inner = np.einsum('i,i->', A, B)

# 2. Outer Product
# Returns a grid of all combinations
outer = np.einsum('i,j->ij', A, B)

# 3. Element-wise Multiplication
# Returns: [1*4, 2*5, 3*6]
mul = np.einsum('i,i->i', A, B)

# 4. Sum
total = np.einsum('i->', A)

print(inner, outer, mul, total, sep='\n**************\n')

32
**************
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
**************
[ 4 10 18]
**************
6


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
# 1. Setup an example path (e.g., a spiral)
t = np.linspace(0, 10, 100)
X = t * np.cos(t)
Y = t * np.sin(t)

# 2. Calculate the distance between consecutive points
dx = np.diff(X)
dy = np.diff(Y)
step_distances = np.sqrt(dx**2 + dy**2)

# 3. Build the cumulative distance (the "odometer" reading)
# Prepend 0 to match the original array length
cum_dist = np.concatenate(([0], np.cumsum(step_distances)))

# 4. Define your new equidistant points
# Let's say we want 50 points perfectly spaced from start to finish
num_samples = 50
new_dist = np.linspace(0, cum_dist[-1], num_samples)

# 5. Interpolate X and Y separately based on the distance
X_equi = np.interp(new_dist, cum_dist, X)
Y_equi = np.interp(new_dist, cum_dist, Y)

print(X_equi, Y_equi, sep='\n**************\n')

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

So, we need to apply two distinct logical filters to the rows of $X$
1. Sum Constraint: The row must sum exactly to $n$.
2. The Integer Constraint: Every element in the row must be a whole number.

In [32]:
def find_multinomial_rows(X, n):
    # 1. Check if the sum of each row equals n
    # We use axis=1 to sum across the columns
    # sum_mask = np.sum(X, axis=1) == n  -> case like a row summing to 9.9999999999 instead of 10
    sum_mask = np.isclose(np.sum(X, axis=1), n)
    
    # 2. Check if all elements in the row are integers
    # np.equal(X, X.astype(int)) compares floats to their truncated versions
    # int_mask = np.all(np.equal(X, np.floor(X)), axis=1)   # extra computation, remains as float
    # int_mask = np.all(np.mod(X, 1) == 0, axis=1)   # fastest (but if root of 25 comes, then it might be 5.00000001 (not 5), resulting False)
    int_mask = np.all(np.isclose(np.mod(X, 1), 0, atol=0.00001), axis=1)
    
    # 3. Combine both constraints (AND logic)
    final_mask = sum_mask & int_mask
    
    # 4. Extract the matching rows
    return X[final_mask]

# Example Usage
n = 10
X = np.array([[5, 5, 0],    # Pass (sums to 10, all ints)
              [4.5, 5.5, 0],# Fail (sums to 10, but has floats)
              [1, 1, 1],    # Fail (all ints, but sums to 3)
              [10, 0, 0]])  # Pass

result = find_multinomial_rows(X, n)
print(result)

[[ 5.  5.  0.]
 [10.  0.  0.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [39]:
def bootstrap_ci(X, n_bootstrap=10000, ci=95):
    # 1. Generate a matrix of random indices with replacement
    # Shape: (n_bootstrap, len(X))
    indices = rng.integers(0, len(X), size=(n_bootstrap, len(X)))
    
    # 2. Resample the data using the indices (Broadcasting)
    resamples = X[indices]
    
    # 3. Compute the mean for each bootstrap sample (Squish across rows)
    sample_means = np.mean(resamples, axis=1)
    
    # 4. Calculate percentiles for the Confidence Interval
    lower_bound = (100 - ci) / 2
    upper_bound = 100 - lower_bound
    
    return np.percentile(sample_means, [lower_bound, upper_bound])

# Usage
X = rng.normal(loc=50, scale=10, size=100)
ci_lower, ci_upper = bootstrap_ci(X)

print(f"95% CI for the mean: [{ci_lower:.2f}, {ci_upper:.2f}]")

95% CI for the mean: [48.82, 52.69]
