# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

In [2]:
hint(1)

hint: import … as


In [3]:
answer(1)

import numpy as np


#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
np.__version__

'2.3.4'

In [6]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: c:/Users/sk/miniforge3/Library/include
    lib directory: c:/Users/sk/miniforge3/Library/lib
    name: blas
    openblas configuration: unknown
    pc file directory: c:/Users/sk/miniforge3/Library/lib/pkgconfig
    version: 3.9.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: c:/Users/sk/miniforge3/Library/include
    lib directory: c:/Users/sk/miniforge3/Library/lib
    name: lapack
    openblas configuration: unknown
    pc file directory: c:/Users/sk/miniforge3/Library/lib/pkgconfig
    version: 3.9.0
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.44.35217
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.44.35217
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.1.5
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    sys

#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [8]:
arr.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.\n    If ``x1.shape != x2.shape``, they must be broadcastable to a common\n    shape (which becomes the shape of the output).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or None,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    This condition is broadcast over the input. At locations where the\n    condition is True, the `out` array will be set to the ufunc result.\n    Elsewhere, the `out` array will retain its original value.\n    Note that if an uninitialized `out` array is created via the defau

In [10]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
arr = np.arange(10,50,1)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [15]:
arr = np.array([1,2,0,0,4,0])
print(  list(filter(lambda x: x!=0, arr))   ) # it will be list, less efficient
# or
print(  np.nonzero(arr) )   # its index

print(  arr[np.nonzero(arr)] )
print(  arr[arr!=0] )   # a boolean mask: [ True  True False False  True False]

[np.int64(1), np.int64(2), np.int64(4)]
(array([0, 1, 4]),)
[1 2 4]
[1 2 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
# uniform [0,1)

# np.random.rand(3,3,3)
# OR
np.random.random((3,3,3))    # consistent with other random functions - shape as tuple , is same a random_sample or randf

array([[[7.85889282e-01, 8.91978831e-01, 8.29731474e-01],
        [3.56927726e-01, 2.04450040e-01, 2.31088007e-01],
        [7.66750323e-01, 4.54241590e-01, 7.36447922e-01]],

       [[3.04984783e-04, 7.50495789e-01, 2.39806191e-01],
        [9.14917561e-01, 1.20317683e-02, 1.61146363e-02],
        [7.88827930e-01, 8.58780778e-01, 5.24804298e-01]],

       [[9.97255928e-01, 1.88796544e-01, 7.18659228e-02],
        [6.63676150e-01, 3.57844786e-01, 7.58625294e-01],
        [8.88600985e-01, 2.60647409e-02, 2.27857986e-01]]])

In [18]:
# OR modern approach
rng = np.random.default_rng(42)
rng.random((3,3,3))             # Uniform [0,1)
# rng.standard_normal((3, 3, 3))    # Standard normal

array([[[0.77395605, 0.43887844, 0.85859792],
        [0.69736803, 0.09417735, 0.97562235],
        [0.7611397 , 0.78606431, 0.12811363]],

       [[0.45038594, 0.37079802, 0.92676499],
        [0.64386512, 0.82276161, 0.4434142 ],
        [0.22723872, 0.55458479, 0.06381726]],

       [[0.82763117, 0.6316644 , 0.75808774],
        [0.35452597, 0.97069802, 0.89312112],
        [0.7783835 , 0.19463871, 0.466721  ]]])

In [19]:
# Or simply use this
np.random.random((3,3,3))

array([[[8.19529911e-01, 7.93958735e-01, 4.75550261e-02],
        [5.31660148e-01, 3.23214498e-01, 7.69005844e-01],
        [1.77188795e-01, 5.33215369e-01, 5.09380620e-01]],

       [[4.43353326e-02, 5.41327094e-01, 7.67754774e-01],
        [1.42368814e-01, 6.82652173e-01, 1.48003790e-01],
        [7.61737008e-01, 8.17728541e-01, 2.06327515e-01]],

       [[8.36289594e-01, 3.28392251e-05, 2.69564370e-01],
        [9.10075795e-01, 4.11429814e-02, 8.26675222e-01],
        [1.86846658e-01, 5.98330253e-01, 1.63656195e-01]]])

## So, re-use ```rng```
 
```rng = np.random.default_rng(42)
rng.random_function(size_in_tuple)```

In [3]:
rng = np.random.default_rng(42)
rng

Generator(PCG64) at 0x147CF5FA880

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [21]:
# arr = np.random.randint(1,100,(10,10))
arr = rng.integers(1,100,(10,10))
arr

array([[ 9, 77, 65, 44, 43, 86,  9, 70, 20, 10],
       [53, 97, 73, 76, 72, 78, 51, 13, 84, 45],
       [50, 37, 19, 92, 78, 64, 40, 82, 54, 44],
       [45, 23, 10, 55, 88,  7, 85, 82, 28, 63],
       [17, 76, 70, 36,  7, 97, 45, 89, 68, 78],
       [76, 20, 37, 47, 50,  5, 55, 16, 74, 68],
       [92, 74, 37, 96, 41, 33, 90, 37,  8, 47],
       [79, 19, 46, 13, 68, 48, 33, 23, 56, 67],
       [94, 44, 16, 83, 63, 70, 10, 31, 77, 83],
       [44, 80, 84, 39, 89, 29, 24, 68, 64, 14]])

In [22]:
# for reduction operations both work but arr.method() is recommended
arr.min() , np.max(arr)

(np.int64(5), np.int64(97))

In [ ]:
np.max(arr) == 99   # treated as False

np.False_

In [24]:
np.True_ == True, np.True_ is True

(np.True_, False)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [25]:
# np.random.rand(30,30).mean()

rng.random((30,30)).mean()

np.float64(0.49492976908403896)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [26]:
arr = np.ones((5,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
arr[1:-1, 1:-1] = 0     # arr[rowsindexes, colmsindexes] or just arr[rowsindexes]
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
Opposite of above

In [28]:
ar = np.ones((5,10))    # alt way of above # OR, np.pad
ar

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
ar[:, [0,-1]] = 0
ar

array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [30]:
ar[[0,-1], :] = 0
ar

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# OR size 3,8 + 2,2 = 5,10
np.pad(np.ones((3,8)), pad_width=1, mode='constant', constant_values=0) 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan) # except != every nan ops = nan
print(np.inf > np.nan)  # Comparisons with nan are always False.
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)   # if deno != 2 and deno is in x/10 fraction - can't be precisely calculated in binary, 
# so cant be exactly same. ex 0.1 = 1/10 , 0.2 = 2/10 , 0.3 = 3/10, 0.4 = 4/10, 
# exactly same for -> 0.5 = 5/10 = 1/2, 0.25 = 25/100 = 1/4

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [33]:
np.diag(v=[1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [35]:
arr = np.zeros((8,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
M = np.fromfunction(lambda i, j: (i + j) % 2, (8, 8), dtype=int) # i-th row, j-th col
M

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [39]:
np.unravel_index(99,(6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
arr = np.fromfunction(lambda i,j: (i+j)%2, (8,8))
arr
# np.tile((8,8), 2) ??

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [50]:
# arr = np.random.random_integers(1,100,(5,5))
arr = rng.integers(1,100,(5,5))
arr

array([[14, 36, 13, 19, 95],
       [ 9, 48, 83, 95, 15],
       [17, 37, 55, 96, 21],
       [17, 26, 87,  3, 38],
       [12, 16, 91,  1, 32]])

In [51]:
( arr - np.mean(arr) ) / np.std(arr)

array([[-0.78401805, -0.0951843 , -0.81532868, -0.62746493,  1.75214259],
       [-0.94057118,  0.2805432 ,  1.37641508,  1.75214259, -0.75270743],
       [-0.69008618, -0.06387368,  0.49971758,  1.78345321, -0.56484368],
       [-0.69008618, -0.40829055,  1.50165758, -1.12843493, -0.03256305],
       [-0.8466393 , -0.7213968 ,  1.62690008, -1.19105618, -0.2204268 ]])

In [55]:
# or directly by
rng.normal(loc=0, scale=1, size=(5,5))
# rng.standard_normal((5,5))

array([[-0.10973418,  0.35272016,  0.76682287,  0.12117795,  0.13076419],
       [ 0.82375313, -0.05928265, -0.72928694, -0.41447307,  0.63391038],
       [ 0.00299329,  0.34020998,  0.67007924, -0.37484146,  0.75624816],
       [ 0.3788426 , -1.23481309,  1.44230479, -0.50074474, -1.65509534],
       [-1.04504371, -1.02104516,  0.05217332, -0.27385051, -0.33683197]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
mera_datatype = np.dtype(
    [("r", np.ubyte),
    ("g", np.ubyte),
    ("b", np.ubyte),
    ("a", np.ubyte)]    # alpha... opaque = 255, full transparent = 0
)
mera_datatype

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
# mat1 = np.random.randint(1,10,(5,3))
# mat2 = np.random.randint(2,20,(3,2))

mat1 = rng.integers(1,10,(5,3))
mat2 = rng.integers(2,20,(3,2))

np.matmul(mat1,mat2)

array([[212, 306],
       [128, 185],
       [ 98, 170],
       [179, 236],
       [211, 336]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
# arr = np.random.randint(1,10,10)

arr = rng.integers(1,10,10)
print(arr)
arr[(3 <= arr) & (arr <= 8)] *= -1  # boolean mask
print(arr)

[1 7 9 7 3 7 1 5 6 5]
[ 1 -7  9 -7 -3 -7  1 -5 -6 -5]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [65]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1)) # actually axis=-1

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [72]:
Z = rng.integers(-10,12,10)
print(Z)
# print(  Z**Z  )            # z^z , Integers to negative integer powers are not allowed
print(  2 << Z >> 2  )
print(  Z <- Z  )         # same as, Z < -Z
print(  1j*Z  )           # -2,-10 --> -0. -2.j    -0.-10.j
print(  Z/1/1 )           # (Z/1)/1
# print(  Z<Z>Z )         # same as (Z < Z) and (Z > Z) / `and` is invalid of np.array
                # The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

[ 3 -9 10 -7  2  7 -5 -5  0  9]
[  4   0 512   0   2  64   0   0   0 256]
[False  True False  True False False  True  True False False]
[ 0. +3.j -0. -9.j  0.+10.j -0. -7.j  0. +2.j  0. +7.j -0. -5.j -0. -5.j
  0. +0.j  0. +9.j]
[ 3. -9. 10. -7.  2.  7. -5. -5.  0.  9.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# all produces warning
a = np.array(0) / np.array(0)
print(a)    # np.float64(nan)
b = np.array(0) // np.array(0)
print(b)    # np.int64(0)
c = np.array([np.nan]).astype(int).astype(float)
print(c)    # 0.000000000000001

nan
0
[-9.22337204e+18]


C:\Users\sk\AppData\Local\Temp\ipykernel_17124\1371233514.py:5: RuntimeWarning: invalid value encountered in divide
  a = np.array(0) / np.array(0)
C:\Users\sk\AppData\Local\Temp\ipykernel_17124\1371233514.py:7: RuntimeWarning: divide by zero encountered in floor_divide
  b = np.array(0) // np.array(0)
C:\Users\sk\AppData\Local\Temp\ipykernel_17124\1371233514.py:9: RuntimeWarning: invalid value encountered in cast
  c = np.array([np.nan]).astype(int).astype(float)


#### 29. How to round a float array, away from zero? (★☆☆)

###### like [-2.3, -1.1, 0.2, 1.4] -> [-3. -2.  1.  2.]

In [ ]:
Z = rng.uniform(-10, 10, size=5)    # uniform gives float
print(Z)

print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 9.98843818  0.32918805 -8.09601826  4.55686598  9.53328156]
[10.  1. -9.  5. 10.]
[10.  1. -9.  5. 10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a1 = np.array([2,10,33,22,1,0,23,1,-1])
print(a1)
a2 = np.array([20,1,3,2,8,00,2,1,-1])
print(a2)

[ 2 10 33 22  1  0 23  1 -1]
[ 2 10 33 22  1  0 23  1 -1]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# change error handling behavior and store previous settings
previous_settings = np.seterr(all='raise')
previous_settings

{'divide': 'raise', 'over': 'raise', 'under': 'raise', 'invalid': 'raise'}

In [ ]:
# Back to sanity
_ = np.seterr(**previous_settings)
_

In [ ]:
# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

In [ ]:
import warnings # silence every warning from every library (NumPy, pandas, sklearn, etc.) in one go
warnings.filterwarnings("ignore")
# warnings.filterwarnings("default")

In [ ]:
Z = np.ones(1) / 0
Z

FloatingPointError: divide by zero encountered in divide

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [4]:
np.sqrt(-1) == np.emath.sqrt(-1)    # nan & 1j

C:\Users\sk\AppData\Local\Temp\ipykernel_18024\2952698182.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)    # nan & 1j


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [6]:
import datetime
tode = datetime.date.today()    # or datetime
tomorrow = tode + datetime.timedelta(days=1)
yesterday = tode - datetime.timedelta(days=1)

print(yesterday)
print(tode)
print(tomorrow) 

2025-11-18
2025-11-19
2025-11-20


In [9]:
# or using np

yesterday = np.datetime64('today') - np.timedelta64(1)
tode      = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday, tode, tomorrow, sep='\n')  # numpy.datetime64

2025-11-18
2025-11-19
2025-11-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
start = np.datetime64('2025-08-01')
end   = np.datetime64('2025-09-01')

dates = np.arange(start, end, dtype='datetime64[D]')    # [D] - days.. ms , W
dates

array(['2025-08-01', '2025-08-02', '2025-08-03', '2025-08-04',
       '2025-08-05', '2025-08-06', '2025-08-07', '2025-08-08',
       '2025-08-09', '2025-08-10', '2025-08-11', '2025-08-12',
       '2025-08-13', '2025-08-14', '2025-08-15', '2025-08-16',
       '2025-08-17', '2025-08-18', '2025-08-19', '2025-08-20',
       '2025-08-21', '2025-08-22', '2025-08-23', '2025-08-24',
       '2025-08-25', '2025-08-26', '2025-08-27', '2025-08-28',
       '2025-08-29', '2025-08-30', '2025-08-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [11]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [14]:
arr = rng.uniform(1, 10, 5)
arr

array([6.79478608, 8.40485452, 4.99072779, 3.0451485 , 5.99126308])

In [ ]:
print(  np.floor(arr)   )
print(  np.trunc(arr)   )   # np.fix(arr)
print(  arr // 1        )
print(  arr.astype(int) )   # np.astype(arr, int)
print(  arr - arr%1     )

[6. 8. 4. 3. 5.]
[6. 8. 4. 3. 5.]
[6. 8. 4. 3. 5.]
[6 8 4 3 5]
[6. 8. 4. 3. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)   #  Broadcast
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1)) # Construct an array by repeating A the number of times given by reps.
                        # 5 → repeat rows 5 times , 1 → repeat columns once
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
# defining generator
def generate():
    for x in range(10):
        yield x
# OR
def generate():
    yield from range(10)

In [ ]:
gen = (x for x in range(10))
np.fromiter(gen, dtype=int, count=-1)   # count=-1 means all

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
arr = rng.uniform(0, 1, 10)
arr2 = np.clip(arr, 1e-6, 1 -1e-6)  # if value is 0 it will be 0.000001
arr2

# more efficient
# eps = np.finfo(float).eps
# arr2 = np.clip(arr, eps, 1 - eps)

array([0.49399082, 0.32986121, 0.14452419, 0.10340297, 0.58764457,
       0.17059297, 0.92512012, 0.58106114, 0.3468698 , 0.59091549])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr = rng.uniform(0, 1+ 1e-10, 10)
sortedarr = np.sort(arr)
print(sortedarr)

[0.04491062 0.43509706 0.99237556 0.89167727 0.74860802 0.89079249
 0.89344664 0.51885836 0.31592905 0.77201243]


In [ ]:
arr.sort()  # in-place sort
arr

array([0.04491062, 0.31592905, 0.43509706, 0.51885836, 0.74860802,
       0.77201243, 0.89079249, 0.89167727, 0.89344664, 0.99237556])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
arr = rng.uniform(0, 1+ 1e-10, 10)
sum(arr)    # fastest 
sum(arr.tolist())
np.add.reduce(arr)  # uses ufunc directly

5.512540281830697

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [ ]:
arr1 = rng.integers(1,10,5)
arr2 = rng.integers(1,10,5)
print( arr1==arr2 )             # these 2 Not good for floats because of rounding errors.
print( np.equal(arr1,arr2) )
print( np.array_equal(arr1,arr2) )  # single boolean


print( np.allclose(arr1,arr2) ) # rtol= , atol= , equal_nan=  False
                                # good for floats as they are never exactly equal.
                                # Works elementwise and then AND-reduces to a single boolean.
print( np.isclose(arr1, arr2).all())  # Same

# print( np.testing.assert_allclose(arr1, arr2) ) # no op, raises error if all not same within tolerance


[False False False False False]
[False False False False False]
False
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [14]:
arr = np.array([1, 2, 3])
arr.flags.writeable = False
arr[0] = 100   # raises ValueError: assignment destination is read-only

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
pts = rng.standard_normal((10, 2))
print(pts)

x = pts[:, 0]
y = pts[:, 1]

# polar coordinates
r = np.sqrt(x**2 + y**2)        # radius
theta = np.arctan2(y, x)        # angle in radians

polar = np.stack((r, theta), axis=1)   # along columns
print(polar)

[[ 2.1416476  -0.40641502]
 [-0.51224273 -0.81377273]
 [ 0.61597942  1.12897229]
 [-0.11394746 -0.84015648]
 [-0.82448122  0.65059279]
 [ 0.74325417  0.54315427]
 [-0.66550971  0.23216132]
 [ 0.11668581  0.2186886 ]
 [ 0.87142878  0.22359555]
 [ 0.67891356  0.06757907]]
[[ 2.17986871 -0.1875375 ]
 [ 0.96157094 -2.13260111]
 [ 1.28608285  1.07132922]
 [ 0.84784841 -1.70560026]
 [ 1.05025723  2.47353747]
 [ 0.92056685  0.63108552]
 [ 0.70484186  2.80594503]
 [ 0.2478715   1.08065428]
 [ 0.8996572   0.25116664]
 [ 0.68226868  0.09921321]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
arr = rng.integers(1,100,10)
arr[arr == arr.max()] = 0
print(arr)

# np.where(arr==max(arr),0,arr)

[78 51 13 84 45 50 37 19  0 78]


array([78, 51, 13,  0, 45, 50, 37, 19,  0, 78])

In [ ]:
a = np.array([[4, 1], [np.nan, 3]]) 
np.argmax(a), np.argmin(a)      # returns first NaN index

(np.int64(2), np.int64(2))

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

np.int64(2)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [4]:
np.iinfo(np.int32).max      # uint16, float64

2147483647

#### 49. How to print all the values of an array? (★★☆)
as, normally numpy shortens large arrays like: array([1, 2, 3, ..., 999, 1000])

In [10]:
np.get_printoptions()

{'edgeitems': 3,
 'threshold': 9223372036854775807,
 'floatmode': 'maxprec',
 'precision': 8,
 'suppress': False,
 'linewidth': 75,
 'nanstr': 'nan',
 'infstr': 'inf',
 'sign': '-',
 'formatter': None,
 'legacy': False,
 'override_repr': None}

In [9]:
np.set_printoptions(threshold=float("inf")) # Or, sys.maxsize or default 1000 (If the array has more than 1000 elements, NumPy will truncate the output and show)
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)